### ISSUE TITLE
SCSS really needed?

### ISSUE THREAD

**Issue by tomByrer** [brianmaierjr/long-haul-astro#4]
Nice theme!

Looking over the SCSS... is it really needed?  Seems most of the things you use, eg CSS-variables, [`clamp()`](https://developer.mozilla.org/en-US/docs/Web/CSS/clamp) etc are all part of CSS standards now....

**Comment by brianmaierjr** [comment]
@tomByrer Probably not! I will be moving away from SCSS in the near future. Thanks for the compliment 🙇🏻
